"""Add recipient_id to chat message

Revision ID: 99049134edcb
Revises: 
Create Date: 2024-06-14 23:59:00.928540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99049134edcb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('chat_messages', sa.Column('recipient_id', sa.Integer(), nullable=True))
#     op.create_foreign_key(None, 'chat_messages', 'users', ['recipient_id'], ['id'])
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_constraint(None, 'chat_messages', type_='foreignkey')
#     op.drop_column('chat_messages', 'recipient_id')
#     # ### end Alembic commands ###


def upgrade():
    with op.batch_alter_table('chat_messages') as batch_op:
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_chat_messages_recipient_id_users', 'users', ['recipient_id'], ['id'])


def downgrade():
    with op.batch_alter_table('chat_messages') as batch_op:
        batch_op.drop_constraint('fk_chat_messages_recipient_id_users', type_='foreignkey')
        batch_op.drop_column('recipient_id')