"""Remove manager_id and creator_user_proxy_id from agent group

Revision ID: bea414eacf04
Revises: ba84d75dd9cc
Create Date: 2024-06-22 00:10:35.506141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bea414eacf04'
down_revision: Union[str, None] = 'ba84d75dd9cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# NotImplementedError: No support for ALTER of constraints in SQLite dialect. Please refer to the batch mode feature which allows for SQLite migrations using a copy-and-move strategy.
# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_constraint(None, 'agent_groups', type_='foreignkey')
#     op.drop_constraint(None, 'agent_groups', type_='foreignkey')
#     op.drop_column('agent_groups', 'creator_user_proxy_id')
#     op.drop_column('agent_groups', 'manager_id')
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('agent_groups', sa.Column('manager_id', sa.INTEGER(), nullable=False))
#     op.add_column('agent_groups', sa.Column('creator_user_proxy_id', sa.INTEGER(), nullable=False))
#     op.create_foreign_key(None, 'agent_groups', 'agents', ['manager_id'], ['id'])
#     op.create_foreign_key(None, 'agent_groups', 'agents', ['creator_user_proxy_id'], ['id'])
#     # ### end Alembic commands ###

def upgrade() -> None:
    with op.batch_alter_table('agent_groups') as batch_op:
        # batch_op.drop_constraint('fk_agent_groups_creator_user_proxy_id_agents', type_='foreignkey')
        # batch_op.drop_constraint('fk_agent_groups_manager_id_agents', type_='foreignkey')
        batch_op.drop_column('creator_user_proxy_id')
        batch_op.drop_column('manager_id')


def downgrade() -> None:
    with op.batch_alter_table('agent_groups') as batch_op:
        batch_op.add_column(sa.Column('manager_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('creator_user_proxy_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_agent_groups_creator_user_proxy_id_agents', 'agents', ['creator_user_proxy_id'], ['id'])
        batch_op.create_foreign_key('fk_agent_groups_manager_id_agents', 'agents', ['manager_id'], ['id'])